framework:
  cache:
    pools:
      tweet_cache:
        adapter: cache.adapter.redis
        default_lifetime: 365
        provider: app.my_custom_redis_provider

services:
  app.my_custom_redis_provider:
    class: \Redis
    factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
    arguments:
      - '%env(resolve:REDIS_URL)%'
      - { retry_interval: 2, timeout: 10 }